# Reference: 
    
Deep Reinforcement Learning with Python

By: Sudharsan Ravichandiran



In [1]:
import gym
import pandas as pd
import random

In [2]:
env = gym.make('FrozenLake-v1')

In [3]:
Q = {}
for s in range(env.observation_space.n):
    for a in range(env.action_space.n):
        Q[(s,a)] = 0.0

In [4]:
def epsilon_greedy(state, epsilon):
    if random.uniform(0,1) < epsilon:
        return env.action_space.sample()
    else:
        return max(list(range(env.action_space.n)), key = lambda x: Q[(state,x)])

In [5]:
alpha = 0.85
gamma = 0.90
epsilon = 0.8

In [6]:
num_episodes = 5000
num_timesteps = 1000

Compute the optimal policy using the SARSA update rule as:

$$ Q(s,a) = Q(s,a) + \alpha (r + \gamma Q(s',a') - Q(s,a)) $$

In [7]:
#for each episode
for i in range(num_episodes):
       
    #initialize the state by resetting the environment
    s = env.reset()[0]
    
    #select the action using the epsilon-greedy policy
    a = epsilon_greedy(s,epsilon)
    
    #for each step in the episode:
    for t in range(num_timesteps):

        #perform the selected action and store the next state information: 
        s_, r, done, truncate,_ = env.step(a)
        
        #select the action a dash in the next state using the epsilon greedy policy:
        a_ = epsilon_greedy(s_,epsilon) 
        
        #compute the Q value of the state-action pair
        Q[(s,a)] += alpha * (r + gamma * Q[(s_,a_)]-Q[(s,a)])
        
        #update next state to current state
        s = s_
        
        #update next action to current action
        a = a_


        #if the current state is the terminal state then break:
        if done or truncate:
            break
     

/opt/conda/lib/python3.10/site-packages/gym/utils/passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


In [8]:
import numpy as np
Q_values = np.zeros([env.observation_space.n, env.action_space.n])

In [9]:
Q_values

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
for i in Q.keys():
    Q_values[i[0]][i[1]] = Q[i]

In [11]:
Q_values

array([[9.26824742e-03, 1.26344969e-04, 6.78513348e-04, 7.47776892e-04],
       [1.66946598e-05, 1.41609781e-02, 2.77136953e-06, 2.83630473e-03],
       [3.34096571e-03, 2.91638895e-03, 5.07243644e-03, 2.63382333e-03],
       [2.99169573e-04, 1.32454318e-03, 4.28595337e-03, 8.67556570e-04],
       [1.30601066e-03, 8.10744655e-06, 5.60263354e-02, 6.94484758e-04],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [4.66225005e-03, 8.26839976e-03, 2.88103460e-02, 5.50308211e-08],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [8.68248851e-03, 2.13504161e-02, 3.70796419e-05, 4.83376797e-03],
       [2.97747662e-02, 8.96517544e-02, 3.01924466e-02, 1.14556457e-02],
       [3.65409308e-01, 2.89656931e-03, 1.71747603e-02, 3.67305126e-04],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.59349506e-02, 8.12391832e-01, 5.34755708e

In [12]:
np.argmax(Q_values, axis=1)

array([0, 1, 2, 2, 2, 0, 2, 0, 1, 1, 0, 0, 0, 1, 1, 0])

Note that on every iteration we update the Q function. After all the iterations, we will have
the optimal Q function. Once we have the optimal Q function then we can extract the
optimal policy by selecting the action which has maximum Q value in each state. 