# TENSORFLOW SYNTAX

Welcome to the first tensorflow tutorial. Tensorflow is a library developed by Google for deploying deep learning models. 

It is an excellent tool for it's job and is the most widely used neural networks deployment library to date. 

We will be covering the basic syntax of tensorflow. For this section of the course, I will recommend a revision of the OOP tutorial of Section 1: Data Wrangling in Python.

In [3]:
import tensorflow as tf
print(tf.__version__) #THIS IS A DUNDER :D

1.7.0


In [6]:
h = tf.constant("Hello ")
w = tf.constant("World")
print(type(h))
print(w)

<class 'tensorflow.python.framework.ops.Tensor'>
Tensor("Const_3:0", shape=(), dtype=string)


In [11]:
with tf.Session()as sess:
    hello = sess.run(h)
    world = sess.run(w)
    result = sess.run(h+w)

    
print(hello)
print(world)
print(result)
#B SHOWS THE BYTES LITERAL

b'Hello '
b'World'
b'Hello World'


In [12]:
num = tf.constant(300)
num1 = tf.constant(200)
with tf.Session() as s:
    result = s.run(num+num1)
print(result)

500


In [18]:
const = tf.constant(10)
fill_mat = tf.fill((4,4),23)
zeros = tf.zeros((4,4))
ones = tf.ones((4,4))
randn = tf.random_normal((4,4), mean=0, stddev = 2)
randu = tf.random_uniform((4,4), minval=0, maxval=2)
operations = [const, fill_mat, zeros, ones, randn, randu]
s = tf.InteractiveSession()
for operation in operations:
    print(s.run(operation))
    print("==============================")

10
[[23 23 23 23]
 [23 23 23 23]
 [23 23 23 23]
 [23 23 23 23]]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
[[-0.08971488 -2.4489367  -0.5885253  -0.65666562]
 [ 1.09055328 -1.13941479 -2.79758286 -3.47856522]
 [ 2.50715923  0.1676262   1.47900081 -2.88066745]
 [-1.13349605  1.09865701 -2.19646621 -2.04656053]]
[[ 1.1987927   0.38766313  0.52204633  0.48264217]
 [ 1.41786647  1.25314617  1.62234402  0.37099385]
 [ 0.40050292  0.0166266   1.1379137   0.49119544]
 [ 0.98850083  0.52497005  0.57458401  1.70849514]]


In [19]:
for operation in operations:
    print(operation.eval())
    print("==============================")

10
[[23 23 23 23]
 [23 23 23 23]
 [23 23 23 23]
 [23 23 23 23]]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
[[ 0.40992892 -0.93508863  0.7543242  -2.13977218]
 [ 2.86707973  0.59480572 -3.8979075   3.71918488]
 [-0.65388137  0.62515414  1.63879418 -1.27152324]
 [-0.95493406  0.00869193  3.17239714 -3.65313268]]
[[ 1.30078387  0.41177964  1.37098885  1.97358489]
 [ 0.87096667  1.02447724  1.37420726  0.49381781]
 [ 0.72756815  1.73479152  0.66269803  1.9307456 ]
 [ 1.4154892   0.11774182  0.92721224  0.53510332]]


In [23]:
mat1 = tf.constant([[1,2],
                  [3,4]])
mat2 = tf.constant([[3],[4]])
mat1.get_shape()
mat2.get_shape()
result = tf.matmul(mat1,mat2)
result = result.eval()
print(result)

[[11]
 [25]]


### WELCOME TO THE END OF THE TUTORIAL

Hope you enjoyed this light introduction to tensorflow. We will dive right into the tensorflow graphs starting from the next tutorial. Until then, enjoy deep learning!

---------------------------------------------------------------------------------------
Copyrights © 2018, All Rights Reserved.
- Author: Mahnoor Anjum.
- Course: The Complete Hands-On Machine Learning Course
- Date Created: 2018-07-08
- Date Modified: -