# **Spit some [tensor] flow**

We need to learn the intricacies of tensorflow to master deep learning

`Let's get this over with`



## So we OHE the last NLP problem, why not do the same and feed it to the neural network? Well because, features in a language, are not independent. 


Let's explore this: 

The quick brown fox jumps over __________________

See you know the end of this sentence because you know the words right? 

well wb this: 

over _____________________

Now we don't know the end of this sentence. 

So in tensorflow, to save computations, we have the embedding layer: 

### Step 1: Words to ints

Nothing deep about deep learning ----> 13 43 32 43 98

### Step 2: Ints to word vector 

13 43 32 43 98 ------> [0.9, 1.2] [-0.4, 0.2] [0.3, 0.3] [-0.4, 0.2] [0.2, 0.5] 

T -----> T x D


### We can use word2vec to make sure the embedding layer has similar words close to each other

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
import cv2
print(tf.__version__)

2.2.0


In [0]:
from tensorflow.keras.layers import Input, Dropout, Dense, Flatten, SimpleRNN, GRU, LSTM
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import SGD, Adam, Adamax
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences


In [0]:
# Get the dataset 
data = ["Hello world", "I ain't saying hello to you", "what's up with all the hellos"]

NameError: ignored

In [0]:
MAX_SIZE = 10000
tokenizer = Tokenizer(num_words=MAX_SIZE)
tokenizer.fit_on_texts(data)
sequences = tokenizer.texts_to_sequences(data)


In [0]:
print(sequences)

[[1, 2], [3, 4, 5, 1, 6, 7], [8, 9, 10, 11, 12, 13]]


In [0]:
print(tokenizer.word_index) 

{'hello': 1, 'world': 2, 'i': 3, "ain't": 4, 'saying': 5, 'to': 6, 'you': 7, "what's": 8, 'up': 9, 'with': 10, 'all': 11, 'the': 12, 'hellos': 13}


In [0]:
T = 4

In [0]:
data = pad_sequences(sequences, 
                    maxlen = T, 
                    padding = 'post')

print(data)

[[ 1  2  0  0]
 [ 5  1  6  7]
 [10 11 12 13]]


In [0]:
data = pad_sequences(sequences, 
                    maxlen = T, 
                    padding = 'pre')

print(data)

[[ 0  0  1  2]
 [ 5  1  6  7]
 [10 11 12 13]]


In [0]:
data = pad_sequences(sequences, 
                    maxlen = T, 
                    truncating = 'pre',
                    padding = 'post')

print(data)

[[ 1  2  0  0]
 [ 5  1  6  7]
 [10 11 12 13]]


In [0]:
data = pad_sequences(sequences, 
                    maxlen = T, 
                    truncating = 'post',
                    padding = 'post')

print(data)

[[ 1  2  0  0]
 [ 3  4  5  1]
 [ 8  9 10 11]]
